---
# Experiment configuration
total_epochs: 50
epochs_per_cycle: 1
wait_for_clients: true
net: FashionMNISTCNN
dataset: fashion-mnist
# Use cuda is available; setting to false will force CPU
cuda: true
experiment_prefix: 'ex-gcp-c20'
output_location: 'output'
tensor_board_active: true
clients_per_round: 10
system:
  federator:
    hostname: '192.168.0.129'
    nic: 'ens4'
  clients:
    amount: 20
