---
# Experiment configuration
total_epochs: 100
epochs_per_cycle: 1
wait_for_clients: true
net: MNISTLR
dataset: mnist
# Use cuda is available; setting to false will force CPU
cuda: false
experiment_prefix: 'experiment_sample'
output_location: 'output'
tensor_board_active: true
clients_per_round: 10
sampler: "p degree"
sampler_args:
  - 0.5     # p degree
  - 42    # random seed
system:
  federator:
    hostname: '192.168.1.102'
    nic: 'en0'
  clients:
    amount: 10
attack:
  compromised_num: 2
  attack_type: 'partial'
  aggregation_rule: 'krum'