---
# Experiment configuration
total_epochs: 30
epochs_per_cycle: 1
wait_for_clients: true
net: Cifar10CNN
dataset: cifar10
# Use cuda is available; setting to false will force CPU
cuda: false
experiment_prefix: 'experiment_baseline'
output_location: 'output'
tensor_board_active: true
clients_per_round: 1
sampler: "limit labels" 
sampler_args:
  - 5     # label limit
  - 42    # random seed
system:
  federator:
    hostname: '192.168.1.104'
    nic: 'wlp4s0'
  clients:
    amount: 10              # must be multiple of the number of labels
